name: weapon
version: '1.0-SNAPSHOT'
main: org.mmga.uglobal.Weapon
api-version: '1.21'
authors: [ qing_chen_you ]
commands:
  UGlobalWeapon:
    description: Select UGlobalWeapon
    usage: /UGlobalWeapon <WeaponType> <x> <y> <z> <power>
    permission: uGlobalWeapon.UGlobalWeapon
